### ISSUE TITLE
An Other Build ?

### ISSUE THREAD

**Issue by anhnvme** [Jupsi/logi_z906_wifi#1]
Hello,
Fist all, thank you for creating this project

I see this guy and his project look like simple https://github.com/LewisSmallwood/IoT-Logitech-Z906
Just once  Male DE-15 instead 2 cable like you

I think you can look into this project then convert to MQTT ?

**Comment by Jupsi** [comment]
Hi, my Project was specially ment to be 2 Cables because i wanted to intergrate the z906 Console.

I do not understand what issue you want to report with this.
Kind regards
