### ISSUE TITLE
Problem getting this to work

### ISSUE THREAD

**Issue by frostworx** [Jupsi/logi_z906_wifi#4]
Hello,
foremost, thank you very much for this great project!

I recently bought a Z906 and shortly after found this cool solution.
Although we double/triple checked the wires, unfortunately we were unable to make it work this weekend.

The esp joins the network as expected and connects to MQTT, which in turn is autodetected by home assistant.
The "Power" state is detected correctly as "Off" but there doesn't seem to be an option to turn it on from Home-Assistant side.

When powering on via console/remote nothing happens at all.
When holding INPUT on the remote for 5 seconds, all input LEDs on the console turn on, so something is happening.

I bought 2 DE-15 (VGA) Female Breakout Board and 2 DE-15 (VGA) Male Breakout Board, so I was able to test [the project IoT-Logitech-Z906](https://github.com/LewisSmallwood/IoT-Logitech-Z906) easily and it works as expected.

I'd love to get your project working, as the MQTT/HA implementation seems perfect, but I'm a bit lost now.
The z906 version returned by the other project is '154', maybe an incompatible firmware?

I would appreciate it if you had some hints on what else we could try.

**Comment by Jupsi** [comment]
Hi,
Power On / Off is only a visible State, not a toggle option because the Console doesnt response to the Serial Message which means it handles power state by itself. As far as i know only the Amplifier can be Powered by a Serial Message.

So turn it on via Button or Remote and then keep it on Powered state.
Are Volume States Changeable from HomeAssistant?

Are you able to keep the ESP32 connected to PC while being connected to the Z906? The USB Serial Print some Logs while turning on etc. those kould help to track the Problem.

When connected to Amplifier and Console and turning on Power it should print a message like "Current Config: ..." or when you change a state in Home Assistant.

Does your Console response when you turn the Volume wheel after powered on? If not its most likely a faulty config which means reseting it should fix it.

**Comment by frostworx** [comment]
Hey,
thank you for your quick help!

Ah, I see, that explains why there is no power on option :)

I can't turn the device on via console/remote, so I can't test if volume control do work in HA.
Good idea with checking the serial logs, but I will probably need some days before I can test it again.

_(the network and MQTT HA connection might have only worked, while the esp was not attached to the z906, but only via serial on the pc, I apologize for the confusion, I'll need to check that again as well)_

Thanks a lot again for your help!

**Comment by Jupsi** [comment]
try connecting the Console to Amp without the esp, reset the config (keep the system in power mode) unplug console and daisychain esp and check if it then works. 

I had this issue you describing while developing and it did cost me a couple of days to figure out why it didnt want to power on.

**Comment by frostworx** [comment]
Thank you very much!
I'll check that shortly (tomorrow?) and will report back.

**Comment by frostworx** [comment]
I reset the config using vanilla console with remote 8 seconds input button press, left the amp powered on & daisychained the esp (connected to pc using moserial with baud 57600):

- the esp ins pingable and connects to mqtt
-  when moving the sliders in HA I see random binary garbage in the serial console, so unfortunately no usable logs for now (also tried other baudrates, maybe the whole problem is simply a broken cable?)
- the console leds remain off, no matter which button I press, pressing the power button produces a sound in the speakers
- the Power status in HA doesn't change and remains Off, every slider state remains "unknown"

_(is the vanilla console supposed to have leds enabled after un- and replugging it standalone? They are all off here, so it is unclear if the am still is powered on after adding the esp)_

**Comment by Jupsi** [comment]
sorry for the late reply.
can you post how the USB Serial Output looks like?

**Comment by frostworx** [comment]
sorry for the lag as well.

I'll try to find the time for another run soonish to get the serial out
_(iirc it was some "garbage" separated by pipes if that helps)_

it is no big deal for me btw. for now, I simply send IR remote codes with my it blaster to HA, which works for the very basic controls I need
_(of course having a back channel to home assistant would be better)_  :)

**Comment by frostworx** [comment]
sorry, didn't have much time.
when pressing several controls via mqtt/HA I get this broken output:

``~pp|`pp|pp|pp|p`|p`~pp|`pp|pp|pp|p`|p`~pp|`pp|pp|pp|p`|p`~pp|`pp|pp|pp|p`|p`~pp|`pp|pp|pp|p`|p`~pp|`pp|pp|pp|p`|p`~pp|`pp|pp|pp|p`|p`~pp|`pp|pp|pp|p`|p`~pp|`pp|pp|pp|p`|p`~pp|`pp|pp|pp|p`|p`~pp|`pp|pp|pp|p`|p`~pp|`pp|`

Probably won't help that much :D

I think it would be a better approach to restart from scratch with more time, so your limited time is not wasted with this issue. Likely I have a broken cable or similar.

Thank you for trying to help me and have a nice weekend!

**Comment by Jupsi** [comment]
probably something is off with your broker settings, the HA message should not lead to trash data

**Comment by frostworx** [comment]
nah, all (multiple) mqtt devices work just fine.

I'll restart from scratch with new cables and a new esp (just in case) in winter(?) :)

thanks a lot for your project and help!

**Comment by Jupsi** [comment]
which HA Method you try with your Log previous? Change Effect or Input will produce alot of data so just try to increase or decrease anyvolume by 1% to remove overhead log
Also does your usb serial report any English log like "Volume Set to" or something?

**Comment by frostworx** [comment]
I tried all volume sliders and effect/input dropdowns.
No, there wasn't any human readable string in the output.
please don't worry, I'm pretty sure it is a hardware problem on my side.

**Comment by frostworx** [comment]
I found out that a "esp32 wroom 32" batch I once bought seems to be faulty.
when testing a different project with one of those (micro usb) esps the serial console was garbage as well.
swapping the esp with a different "esp32 wroom 32" (with usb-c) fixes the broken serial console for both projects.

The commands sent from HA are shown correctly in the serial console now,
but controlling via console/ir remote doesn't do anything (only some crackling in the speakers, leds remain off).

 We'll retry with fresh cables (soonish) as this seems to be a wiring issue.

**Comment by EpicLPer** [comment]
@frostworx I had this loud pop/crackling issue when the amp couldn't talk to the console properly, so it might try to send a sort of hard reset command to the amp without first muting the output resulting in that pop? Not sure.
But yeah, it might be an issue with your wiring and the console not being routed through to the amp directly.

**Comment by Jupsi** [comment]
Thats nice to hear.
If the Console doesnt response reset the Console with no ESP inbetween

I hope i can fix that by next year i know this is annoying.

**Comment by frostworx** [comment]
Thank you both for your help @EpicLPer and @Jupsi! Very appreciated :)

The explanation with the hard reset attempt sounds reasonable.
When the new cables don't help, I'll try the console reset again for sure.

**Comment by LucianTothezan** [comment]
i am following closely the developpement You  guys are doing. I am very interrested in this project to be able to implement it myself.

**Comment by LucianTothezan** [comment]
Hello all. I have successfully daisy chained the esp32 board with the z906 and I must say it works flawlessly. I am now able to both control the system from the IR remote and from HA, via a broadlink r3mini remote. I am actually using the information related to the status of the system (on, off,  values for volumes, etc) and I have created a dashboard on a tablet that emulates the physical remote of both tv and z906. The status of the z906 is taken from your binary sensor for that, and based on that status I use an automation to turn the system on or off together with the tv. Very happy with this layout. Thank You again for this project. The layout visible in the prins screens is taken from the phone but the layout is optimized for the tablet to be displayed correctly.
![Screenshot_20241208-102253](https://github.com/user-attachments/assets/5abcabd8-b1c1-455d-970a-b33eaccd6b53)
![Screenshot_20241208-102217](https://github.com/user-attachments/assets/1913477d-d9b7-47d7-9c4a-c14258365513)

**Comment by frostworx** [comment]
congratulations @LucianTothezan 

I haven't touched the project again yet, but apparently my problem is on my hardware side, so I guess this issue is invalid.

thank you all for trying to help!


edit: when I find something out which might help others, I'll post it here of course...

**Comment by LucianTothezan** [comment]
> I found out that a "esp32 wroom 32" batch I once bought seems to be faulty. when testing a different project with one of those (micro usb) esps the serial console was garbage as well. swapping the esp with a different "esp32 wroom 32" (with usb-c) fixes the broken serial console for both projects.
> 
> The commands sent from HA are shown correctly in the serial console now, but controlling via console/ir remote doesn't do anything (only some crackling in the speakers, leds remain off).
> 
> We'll retry with fresh cables (soonish) as this seems to be a wiring issue.

It is a silly question but ... Did You check if the connectors are not considered in reverse in regards to the wiring given in the project: male as subwoofer , female as console?

**Comment by frostworx** [comment]
> 
> It is a silly question but ... Did You check if the connectors are not considered in reverse in regards to the wiring given in the project: male as subwoofer , female as console?

Yeah, I did indeed, but thank you for trying to help :)

No big deal really, I'm sure it'll work on the next fresh try. 

until then the broadlink blaster will be enough

**Comment by Jupsi** [comment]
I just hooked mine up to my PC because i had to update my MQTT Settings and did some research.
 Have you set your Serial Baud Rate to 115200 on Arduino IDE ?

Also my Garbage Data Problem seem to be gone for whatever reason. I can restart my Console without any issues..

**Comment by frostworx** [comment]
sorry for the delay. unfortunately I did not have the chance to look into this again yet, but yeah, I tried several baud rates, so likely also 115200.
again thank you very much for all your help here! you should not really worry though, I'm sure I can get it to work :)
