### ISSUE TITLE
ESP power supply

### ISSUE THREAD

**Issue by RowCZ** [Jupsi/logi_z906_wifi#7]
Maybe stupid question but I am not sure, the ESP is powered independently by USB or from 3.3V from pin 11?
If independently, did you try to "steal" power for ESP form 3.3V rail?
Thanks.

**Comment by Jupsi** [comment]
Hi,
i powered it independently by USB because in my research somebody said the 3.3V in the DB15 Cable does not provide enough power for Console and ESP together.

Kind Regards

**Comment by RowCZ** [comment]
Ok, thanks
